eureka:
  server:
    renewal-percent-threshold: 0.60
  instance:
    hostname: slave
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8751/eureka/
spring:
  profiles: slave
  application:
    name: eurka-server
