eureka:
  server:
    renewal-percent-threshold: 0.60
  instance:
    hostname: master
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8752/eureka/
spring:
  profiles: master
  application:
    name: eurka-server
