eureka:
  server:
    renewal-percent-threshold: 0.60
  instance:
    hostname: slave
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://master:8752/eureka/
spring:
  profiles: slave
  application:
    name: eurka-server
